#include "dvdaf.h"
#include "Constants.h"
#include "Vendor.h"
#include "Field.h"
#include "ext/standard/info.h"

ZEND_BEGIN_ARG_INFO_EX(only_first_by_ref, 0, ZEND_RETURN_VALUE, static_cast<unsigned int>(-1))
	ZEND_ARG_PASS_INFO(1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(exec_force_ref, 0, ZEND_RETURN_VALUE, static_cast<unsigned int>(-1))
	ZEND_ARG_PASS_INFO(0)
	ZEND_ARG_PASS_INFO(1)
	ZEND_ARG_PASS_INFO(1)
ZEND_END_ARG_INFO();

static zend_function_entry dvdaf3_functions[] = {
	PHP_FE(dvdaf3_getvalue			,NULL)
	PHP_FE(dvdaf3_translatestring	,NULL)
	PHP_FE(dvdaf3_strlen			,NULL)
	PHP_FE(dvdaf3_substr			,NULL)
	PHP_FE(dvdaf3_textarea2db		,NULL)
	PHP_FE(dvdaf3_db2textarea		,NULL)
	PHP_FE(dvdaf3_itod				,NULL)
	PHP_FE(dvdaf3_decode			,NULL)
	PHP_FE(dvdaf3_getbrowserfield	,NULL)
	PHP_FE(dvdaf3_getbrowserow		,only_first_by_ref)
	//PHP_FE(dvdaf3_validateinput		,validateinput_force_ref)
	//PHP_FE(dvdaf3_validateinput2		,NULL)
	PHP_FE(dvdaf3_logrequeststr		,NULL)
	PHP_FE(dvdaf3_exec				,exec_force_ref)
	PHP_FE(dvdaf3_stardescription	,NULL)
	PHP_FE(dvdaf3_encoderegion		,NULL)
	PHP_FE(dvdaf3_gettableid		,NULL)
	PHP_FE(dvdaf3_getfieldid		,NULL)
	PHP_FE(dvdaf3_getfieldcolumn	,NULL) // dvdaf3_columname
	PHP_FE(dvdaf3_getfielddefault	,NULL) // dvdaf3_getdefault
	PHP_FE(dvdaf3_getfieldlabel		,NULL) // dvdaf3_getlabel
	PHP_FE(dvdaf3_getfieldseparator	,NULL) // dvdaf3_fieldseparator
	{NULL, NULL, NULL}
};

zend_module_entry dvdaf3_module_entry = {
	STANDARD_MODULE_HEADER,
	PHP_DVDAF3_EXTENSION_NAME,		// Extension Name
	dvdaf3_functions,				// PHP Exposed Functions
	PHP_MINIT(dvdaf3),				// MINIT		- Callback for the first time a module is loaded into a particular instance of PHP.
	NULL,							// MSHUTDOWN	- Callback when a module is unloaded from a particular instance of PHP, typically during final shutdown.
	NULL,							// RINIT		- Callback at the beginning of each request.
	NULL,							// RSHUTDOWN	- Callback at the end of each request.
	PHP_MINFO(dvdaf3),				// MINFO		- Callback when the phpinfo() function is called
	PHP_DVDAF3_EXTENSION_VERSION,	// Extension Version
	STANDARD_MODULE_PROPERTIES
};

#ifdef COMPILE_DL_DVDAF
	ZEND_GET_MODULE(dvdaf3) // Needed for DLL built
#endif

#define CONSTANT(c) REGISTER_LONG_CONSTANT(#c, c, CONST_CS | CONST_PERSISTENT)
PHP_MINIT_FUNCTION(dvdaf3)
{
	CONSTANT(DVDAF3_GET);
	CONSTANT(DVDAF3_POST);
	CONSTANT(DVDAF3_COOKIE);
	CONSTANT(DVDAF3_ENV);
	CONSTANT(DVDAF3_SERVER);
	CONSTANT(DVDAF3_FILES);

	CONSTANT(DVDAF3_INT);
	CONSTANT(DVDAF3_FLOAT);
	CONSTANT(DVDAF3_BOOLEAN);

	CONSTANT(DVDAF3_ASCII_2_UTF8);
	CONSTANT(DVDAF3_SEARCH);
	CONSTANT(DVDAF3_NO_TRANSLATION);
	CONSTANT(DVDAF3_URL);

	CONSTANT(DVDAF3_TRUNCATE_LINE);
	CONSTANT(DVDAF3_LOWER);
	CONSTANT(DVDAF3_SEARCH_COMMAS);
	CONSTANT(DVDAF3_NO_AMP_EXPANSION);

	CONSTANT(DVDAF3_DICT_AMZ_COUNTRY);
	CONSTANT(DVDAF3_DICT_DVD_COUNTRY);
	CONSTANT(DVDAF3_DICT_DISPOSITION);
	CONSTANT(DVDAF3_DICT_EXPIRE_REASON);
	CONSTANT(DVDAF3_DICT_FEATURE_CD);
	CONSTANT(DVDAF3_DICT_FRAME_CONVERSION);
	CONSTANT(DVDAF3_DICT_IMG_SUITABILITY);
	CONSTANT(DVDAF3_DICT_IMG_TREATMENT);
	CONSTANT(DVDAF3_DICT_LANGUAGE);
	CONSTANT(DVDAF3_DICT_MEDIA_TYPE);
	CONSTANT(DVDAF3_DICT_PIC_CODE);
	CONSTANT(DVDAF3_DICT_PIC_TYPE);
	CONSTANT(DVDAF3_DICT_PUBLIC);
	CONSTANT(DVDAF3_DICT_FILM_RATING);
	CONSTANT(DVDAF3_DICT_REGION);
	CONSTANT(DVDAF3_DICT_RELEASE_STATUS);
	CONSTANT(DVDAF3_DICT_REQUEST_DVD);
	CONSTANT(DVDAF3_DICT_REQUEST_FILM);
	CONSTANT(DVDAF3_DICT_REQUEST_PERSON);
	CONSTANT(DVDAF3_DICT_REQUEST_PUB);
	CONSTANT(DVDAF3_DICT_REQUEST_PIC);
	CONSTANT(DVDAF3_DICT_PERSON_ROLE);
	CONSTANT(DVDAF3_DICT_ROLE_DIR);
	CONSTANT(DVDAF3_DICT_ROLE_CAST);
	CONSTANT(DVDAF3_DICT_ROLE_CREW);
	CONSTANT(DVDAF3_DICT_SOUND_SYSTEM);
	CONSTANT(DVDAF3_DICT_SOURCE);
	CONSTANT(DVDAF3_DICT_SURROUND_MODE);
	CONSTANT(DVDAF3_DICT_TRADE_LOAN);
	CONSTANT(DVDAF3_DICT_VIDEO_MODE);
	CONSTANT(DVDAF3_DICT_YES_NO);
	CONSTANT(DVDAF3_DICT_GENRE);
	CONSTANT(DVDAF3_DICT_GENRE_LOWER);
	CONSTANT(DVDAF3_DICT_BIRTH_COUNTRY);

	CONSTANT(DVDAF3_PRES_DVD_MULTI);
	CONSTANT(DVDAF3_PRES_DVD_PRINT);
	CONSTANT(DVDAF3_PRES_DVD_ONE);
	CONSTANT(DVDAF3_PRES_DVD_WHO);
	CONSTANT(DVDAF3_PRES_PRICE_MULTI);
	CONSTANT(DVDAF3_PRES_PRICE_ONE);
	CONSTANT(DVDAF3_PRES_DVD_UPC);

	CONSTANT(DVDAF3_FLG_HIGHLIGHTROW);
	CONSTANT(DVDAF3_FLG_HIGHRES);
	CONSTANT(DVDAF3_FLG_COLLECTION);
	CONSTANT(DVDAF3_FLG_DOINPUT);
	CONSTANT(DVDAF3_FLG_INITTOPEN);
	CONSTANT(DVDAF3_FLG_STARMEMBER);
	CONSTANT(DVDAF3_FLG_NOCOMMENT);
	CONSTANT(DVDAF3_FLG_SHOWRELEASEDT);
	CONSTANT(DVDAF3_FLG_SKIPOUTOFPRINT);
	CONSTANT(DVDAF3_FLG_EXPANDTITLE);
	CONSTANT(DVDAF3_FLG_NOPRICE);
	CONSTANT(DVDAF3_FLG_EBAYLINK);
	CONSTANT(DVDAF3_FLG_COL1_SKIP);
	CONSTANT(DVDAF3_FLG_HIDEBESTPRICE);

//	CONSTANT(DVDAF3_CLOSED_TAGS_ONLY);
	CField::InitTableRange();

	return SUCCESS;
}
#undef CONSTANT

PHP_MINFO_FUNCTION(dvdaf3)
{
	php_info_print_table_start();
	php_info_print_table_header(2, "DVD Aficionado support", "enabled");
	php_info_print_table_end();
}
