#include "Field.h"
#include "Tbl.h"
#include "Domain.h"

#define FIELD__(column,domain,table,format,label,parm,def,derivfun,derivcol) {	 \
	CField::eField_ ## table ## _ ## column		/* CField::eType	_FieldId		*/,\
	CTbl::eTable_ ## table						/* int				_TableId		*/,\
	CDomain::eDomain_ ## domain					/* int				_DomainId		*/,\
	{SS(#column)}								/* CStaticStr		_Column			*/,\
	{SS(#table "_" #column)}					/* CStaticStr		_Alias			*/,\
	{SS(#table "_" #column)}					/* CStaticStr		_Input			*/,\
	{SS(#label)}								/* CStaticStr		_Label			*/,\
	CField::eFormat_ ## format					/* CField::eFormat	_Format			*/,\
	{SS(def)}									/* CStaticStr		_Default		*/,\
	parm										/* unsigned int		_Parm			*/,\
	derivfun									/* FDeriveField		*_CalcDerived	*/,\
	CField::eField_ ## table ## _ ## derivcol	/* int				_DerivedFieldId	*/}

#define FIELD_2(column,domain,table,format,label,parm,def,derivfun,derivcol) {	 \
	CField::eField_ ## table ## _ ## column		/* CField::eType	_FieldId		*/,\
	CTbl::eTable_ ## table						/* int				_TableId		*/,\
	CDomain::eDomain_ ## domain					/* int				_DomainId		*/,\
	{SS(#column)}								/* CStaticStr		_Column			*/,\
	{SS(#table "_" #column)}					/* CStaticStr		_Alias			*/,\
	{SS(#table #column)}						/* CStaticStr		_Input			*/,\
	{SS(#label)}								/* CStaticStr		_Label			*/,\
	CField::eFormat_ ## format					/* CField::eFormat	_Format			*/,\
	{SS(def)}									/* CStaticStr		_Default		*/,\
	parm										/* unsigned int		_Parm			*/,\
	derivfun									/* FDeriveField		*_CalcDerived	*/,\
	CField::eField_ ## table ## _ ## derivcol	/* int				_DerivedFieldId	*/}

#define FIELDzz(zfield,column,table,format,label) {	 \
	CField::eField_zz_ ## zfield				/* CField::eType	_FieldId		*/,\
	CTbl::eTable_zz								/* int				_TableId		*/,\
	CDomain::eDomain_none						/* int				_DomainId		*/,\
	{SS(#column)}								/* CStaticStr		_Column			*/,\
	{SS(#table "_" #column)}					/* CStaticStr		_Alias			*/,\
	{SS("zz_" #column)}							/* CStaticStr		_Input			*/,\
	{SS(#label)}								/* CStaticStr		_Label			*/,\
	CField::eFormat_ ## format					/* CField::eFormat	_Format			*/,\
	{0, 0}										/* CStaticStr		_Default		*/,\
	0											/* unsigned int		_Parm			*/,\
	0											/* FDeriveField		*_CalcDerived	*/,\
	CField::eField_zz_none						/* int				_DerivedFieldId	*/}

#define eField_zz_0			eField_zz_none
#define eField_a_0			eField_zz_none
#define eField_za_0			eField_zz_none
#define eField_f_0			eField_zz_none
#define eField_zf_0			eField_zz_none
#define eField_e_0			eField_zz_none
#define eField_ze_0			eField_zz_none
#define eField_c_0			eField_zz_none
#define eField_zc_0			eField_zz_none
#define eField_r_0			eField_zz_none
#define eField_zr_0			eField_zz_none
#define eField_t_0			eField_zz_none
#define eField_zt_0			eField_zz_none
#define eField_p_0			eField_zz_none
#define eField_zp_0			eField_zz_none
#define eField_pr_0			eField_zz_none
#define eField_b_0			eField_zz_none
#define eField_b2_0			eField_zz_none
#define eField_u_0			eField_zz_none
#define eField_zu_0			eField_zz_none
#define eField_v_0			eField_zz_none
#define eField_zv_0			eField_zz_none
#define eField_d_0			eField_zz_none
#define eField_zd_0			eField_zz_none

const CField::t_field CField::gp_field[CField::eField_total_types] = {
	// ------------------------------
	// dvd
	// ------------------------------
FIELD__(none				,none					,zz,default				,&nbsp;,0,"",0,0),
FIELD__(dvd_id				,obj_id					,a ,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(version_id			,version_id				,a ,default				,Current version,0,"",0,0),
FIELD__(dvd_title_tmpl		,dvd_title_tmpl			,a ,default				,Title template,CField::eDbDashOnEmpty,"",0,0),
FIELD__(bonus_items			,bonus_items			,a ,default				,Bonus items,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_notes			,dvd_notes				,a ,default				,DVD notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_title			,dvd_title				,a ,default				,Title,CField::eDbDashOnEmpty,"",deriveTitle,dvd_title_nocase),
FIELD__(dvd_title_nocase	,dvd_title_nocase		,a ,default				,Search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_title_sort		,film_title_single_sort	,a ,default				,Sort string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(url					,url					,a ,default				,DVDAF URL,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_year		,year					,a ,default				,Film release year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(film_rel_year_end	,year					,a ,default				,Last season year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(director			,director_list			,a ,default				,Director,CField::eDbDashOnEmpty,"",deriveDirector,director_nocase),
FIELD__(director_nocase		,director_list_nocase	,a ,default				,Director search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(publisher			,publisher_list			,a ,default				,DVD Publisher,CField::eDbDashOnEmpty,"",derivePublisher,publisher_nocase),
FIELD__(publisher_nocase	,publisher_list_nocase	,a ,default				,DVD Publisher search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(orig_language		,language_list			,a ,default				,Original primary language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(language_add		,language_list			,a ,default				,Original additional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(country				,country_list			,a ,default				,DVD country,CField::eDbDashOnEmpty,"us",deriveCountry,country_block),
FIELD__(country_block		,country_list_2			,a ,default				,DVD country block,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rating			,film_rating			,a ,default				,Film rating,CField::eDbDashOnEmpty,"",0,0),
FIELD__(region_mask			,region_mask			,a ,dvd_region_mask		,Region,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(genre				,genre_cd				,a ,default				,Primary genre,0,"",0,0),
FIELD__(media_type			,media_type				,a ,default				,Media type,0,"",0,0),
FIELD__(num_titles			,num_titles				,a ,default				,Number of titles,0,"1",0,0),
FIELD__(num_disks			,num_disks				,a ,default				,Number of discs,CField::eDbZeroOnEmpty,"1",0,0),
FIELD__(source				,dvd_source				,a ,default				,Source,0,"",0,0),
FIELD__(rel_status			,rel_status_cd			,a ,default				,DVD release status,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_dd			,film_rel_dd			,a ,default				,Film release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_rel_dd			,dvd_rel_dd				,a ,default				,DVD release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_oop_dd			,dvd_rel_dd				,a ,default				,Out of print date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id_list			,a ,default				,Imdb links,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,a ,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_status			,pic_type				,a ,default				,Picture status,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,a ,default				,Picture filename,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_count			,num_pics				,a ,default				,Number of pictures,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(list_price			,money					,a ,default				,List price,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sku					,sku_list				,a ,default				,Studio product code,CField::eDbDashOnEmpty,"",0,0),
FIELD__(upc					,upc_list				,a ,default				,UPC,CField::eDbDashOnEmpty,"",0,0),
FIELD__(asin				,asin					,a ,default				,ASIN,CField::eDbDashOnEmpty,"",0,0),
FIELD__(amz_country			,amz_country			,a ,default				,Amazon country,CField::eDbDashOnEmpty,"",0,0),
FIELD__(best_price			,money					,a ,default				,Best price,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(amz_rank			,num_counter			,a ,default				,Amazon ranking,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(mod_flags			,mod_flags				,a ,default				,Mod flags,CField::eDbDashOnEmpty,"",0,0),
FIELD__(migrated_ind		,bool_check				,a ,default				,Title migrated,0,"",0,0),
FIELD__(dvd_created_tm		,datetime				,a ,default				,Created on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(dvd_updated_tm		,datetime				,a ,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(dvd_updated_by		,user_id				,a ,default				,Last updated by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(last_justify		,justify_narrow			,a ,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_verified_tm		,datetime				,a ,default				,Verified on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(dvd_verified_by		,user_id				,a ,default				,Verified by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(verified_version	,version_id				,a ,default				,Last verified version,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(dvd_edit_id			,edit_id				,a ,default				,DVD audit id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,a ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(edit_id				,edit_id				,za,default				,DVD audit id,0,"",0,0),
FIELD__(dvd_id				,obj_id					,za,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(request_cd			,request_cd_dvd			,za,default				,Request type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(disposition_cd		,disposition_cd			,za,default				,Disposition,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_id			,user_id				,za,default				,Proposer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_notes		,proposer_notes			,za,default				,Proposer notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposed_tm			,datetime				,za,default				,Proposed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(updated_tm			,datetime				,za,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(reviewer_id			,user_id				,za,default				,Reviewer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewer_notes		,reviewer_notes			,za,default				,Moderator notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewed_tm			,datetime				,za,default				,Reviewed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,za,default				,Version,0,"",0,0),
FIELD__(dvd_title_tmpl		,dvd_title_tmpl			,za,default				,Title template,CField::eDbDashOnEmpty,"",0,0),
FIELD__(bonus_items			,bonus_items			,za,default				,Bonus items,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_notes			,dvd_notes				,za,default				,DVD notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_title			,dvd_title				,za,default				,Title,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_year		,year					,za,default				,Film release year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(film_rel_year_end	,year					,za,default				,Last season year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(director			,director_list			,za,default				,Director,CField::eDbDashOnEmpty,"",0,0),
FIELD__(publisher			,publisher_list			,za,default				,DVD Publisher,CField::eDbDashOnEmpty,"",0,0),
FIELD__(orig_language		,language_list			,za,default				,Original primary language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(language_add		,language_list			,za,default				,Original additional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(country				,country_list			,za,default				,DVD country,CField::eDbDashOnEmpty,"us",0,0),
FIELD__(film_rating			,film_rating			,za,default				,Film rating,CField::eDbDashOnEmpty,"",0,0),
FIELD__(region_mask			,region_mask			,za,dvd_region_mask		,Region,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(genre				,genre_cd				,za,default				,Primary genre,0,"",0,0),
FIELD__(media_type			,media_type				,za,default				,Media type,0,"",0,0),
FIELD__(num_titles			,num_titles				,za,default				,Number of titles,0,"1",0,0),
FIELD__(num_disks			,num_disks				,za,default				,Number of discs,CField::eDbZeroOnEmpty,"1",0,0),
FIELD__(source				,dvd_source				,za,default				,Source,0,"",0,0),
FIELD__(rel_status			,rel_status_cd			,za,default				,DVD release status,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_dd			,film_rel_dd			,za,default				,Film release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_rel_dd			,dvd_rel_dd				,za,default				,DVD release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_oop_dd			,dvd_rel_dd				,za,default				,Out of print date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id_list			,za,default				,Imdb links,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,za,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(list_price			,money					,za,default				,List price,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sku					,sku_list				,za,default				,Studio product code,CField::eDbDashOnEmpty,"",0,0),
FIELD__(upc					,upc_list				,za,default				,UPC,CField::eDbDashOnEmpty,"",0,0),
FIELD__(asin				,asin					,za,default				,ASIN,CField::eDbDashOnEmpty,"",0,0),
FIELD__(amz_country			,amz_country			,za,default				,Amazon country,CField::eDbDashOnEmpty,"",0,0),
FIELD__(update_justify		,justify_wide			,za,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,za,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// film
	// ------------------------------
FIELD__(film_id				,obj_id					,f ,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(version_id			,version_id				,f ,default				,Current version,0,"",0,0),
FIELD__(feature_cd			,feature_cd				,f ,default				,Feature type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_title			,film_title				,f ,default				,Film title,0,"",0,0),
FIELD__(url					,url					,f ,default				,DVDAF URL,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_year		,year					,f ,default				,Release year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(film_rel_year_end	,year					,f ,default				,Final season year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(episode_of			,obj_id					,f ,default				,Series id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(episode_of_title	,episode_of_title		,f ,default				,Series title,CField::eDbDashOnEmpty,"",0,0),
FIELD__(director			,director_list			,f ,default				,Director,CField::eDbDashOnEmpty,"",0,0),
FIELD__(cast				,cast_list				,f ,default				,Cast,CField::eDbNullOnEmpty,"",0,0),
FIELD__(orig_language		,language_list			,f ,default				,Original primary language,CField::eDbDashOnEmpty,"en",0,0),
FIELD__(language_add		,language_list			,f ,default				,Original additional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(aspect_ratio_ori	,aspect_ratio			,f ,default				,Reference aspect ratio,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(run_time_ori		,runtime				,f ,default				,Reference runtime,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(genre				,genre_list				,f ,default				,Genre,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_dd			,film_rel_dd			,f ,default				,Release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,f ,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,f ,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id				,f ,default				,Imdb link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,f ,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_status			,pic_type				,f ,default				,Picture status,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,f ,default				,Picture filename,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_count			,num_pics				,f ,default				,Number of pictures,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(mod_flags			,mod_flags				,f ,default				,Mod flags,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_created_tm		,datetime				,f ,default				,Created on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(film_updated_tm		,datetime				,f ,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(film_updated_by		,user_id				,f ,default				,Last updated by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(last_justify		,justify_narrow			,f ,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_verified_tm	,datetime				,f ,default				,Verified on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(film_verified_by	,user_id				,f ,default				,Verified by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(verified_version	,version_id				,f ,default				,Last verified version,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(film_edit_id		,edit_id				,f ,default				,Film audit id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,f ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_edit_id		,edit_id				,zf,default				,Film audit id,0,"",0,0),
FIELD__(film_id				,obj_id					,zf,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(request_cd			,request_cd_film		,zf,default				,Request type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(disposition_cd		,disposition_cd			,zf,default				,Disposition,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_id			,user_id				,zf,default				,Proposer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_notes		,proposer_notes			,zf,default				,Proposer notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposed_tm			,datetime				,zf,default				,Proposed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(updated_tm			,datetime				,zf,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(reviewer_id			,user_id				,zf,default				,Reviewer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewer_notes		,reviewer_notes			,zf,default				,Moderator notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewed_tm			,datetime				,zf,default				,Reviewed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,zf,default				,Version,0,"",0,0),
FIELD__(feature_cd			,feature_cd				,zf,default				,Feature type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_title			,film_title				,zf,default				,Film title,0,"",0,0),
FIELD__(film_rel_year		,year					,zf,default				,Release year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(film_rel_year_end	,year					,zf,default				,Final season year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(episode_of			,obj_id					,zf,default				,Series id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(director			,director_list			,zf,default				,Director,CField::eDbDashOnEmpty,"",0,0),
FIELD__(cast				,cast_list				,zf,default				,Cast,CField::eDbNullOnEmpty,"",0,0),
FIELD__(orig_language		,language_list			,zf,default				,Original primary language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(language_add		,language_list			,zf,default				,Original additional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(aspect_ratio_ori	,aspect_ratio			,zf,default				,Reference aspect ratio,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(run_time_ori		,runtime				,zf,default				,Reference runtime,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(genre				,genre_list				,zf,default				,Genre,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_rel_dd			,film_rel_dd			,zf,default				,Release date,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,zf,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,zf,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id				,zf,default				,Imdb link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,zf,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(update_justify		,justify_wide			,zf,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zf,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// edition
	// ------------------------------
FIELD__(dvd_id				,obj_id					,e ,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(film_id				,obj_id					,e ,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(edition_seq			,seq_num				,e ,default				,Edition seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(alias_of			,obj_id					,e ,default				,Alias of,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(prim_title_seq		,seq_num_small			,e ,default				,Title to use,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(prim_title			,film_title				,e ,default				,Title to use,CField::eDbDashOnEmpty,"",0,0),
FIELD__(editon_notes		,edition_notes			,e ,default				,Edition notes,CField::eDbNullOnEmpty,"",0,0),
FIELD__(language_dubbed		,language_list			,e ,default				,Dubbed language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(language_opt		,language_list			,e ,default				,Optional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(subtitles_fixed		,language_list			,e ,default				,Fixed Subtitles,CField::eDbDashOnEmpty,"",0,0),
FIELD__(subtitles_opt		,language_list			,e ,default				,Optional Subtitles,CField::eDbDashOnEmpty,"",0,0),
FIELD__(sound_system		,sound_system			,e ,default				,Sound system,CField::eDbDashOnEmpty,"",0,0),
FIELD__(surround_mode		,surround_mode			,e ,default				,Surround mode,CField::eDbDashOnEmpty,"",0,0),
FIELD__(video_mode			,video_mode				,e ,default				,Video mode,CField::eDbDashOnEmpty,"",0,0),
FIELD__(aspect_ratio		,aspect_ratio			,e ,default				,Aspect ratio,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(frame_conversion	,frame_conversion		,e ,default				,Frame conversion,CField::eDbDashOnEmpty,"",0,0),
FIELD__(run_time			,runtime				,e ,default				,Runtime,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,e ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(edit_id				,edit_id				,ze,default				,DVD audit id,0,"",0,0),
FIELD__(film_id				,obj_id					,ze,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(edition_seq			,seq_num				,ze,default				,Edition seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(dvd_id				,obj_id					,ze,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,ze,default				,Version,0,"",0,0),
FIELD__(alias_of			,obj_id					,ze,default				,Alias of,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(prim_title_seq		,seq_num_small			,ze,default				,Title to use,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(editon_notes		,edition_notes			,ze,default				,Edition notes,CField::eDbNullOnEmpty,"",0,0),
FIELD__(language_dubbed		,language_list			,ze,default				,Dubbed language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(language_opt		,language_list			,ze,default				,Optional language,CField::eDbDashOnEmpty,"",0,0),
FIELD__(subtitles_fixed		,language_list			,ze,default				,Fixed Subtitles,CField::eDbDashOnEmpty,"",0,0),
FIELD__(subtitles_opt		,language_list			,ze,default				,Optional Subtitles,CField::eDbDashOnEmpty,"",0,0),
FIELD__(sound_system		,sound_system			,ze,default				,Sound system,CField::eDbDashOnEmpty,"",0,0),
FIELD__(surround_mode		,surround_mode			,ze,default				,Surround mode,CField::eDbDashOnEmpty,"",0,0),
FIELD__(video_mode			,video_mode				,ze,default				,Video mode,CField::eDbDashOnEmpty,"",0,0),
FIELD__(aspect_ratio		,aspect_ratio			,ze,default				,Aspect ratio,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(frame_conversion	,frame_conversion		,ze,default				,Frame conversion,CField::eDbDashOnEmpty,"",0,0),
FIELD__(run_time			,runtime				,ze,default				,Runtime,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,ze,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// edpub
	// ------------------------------
FIELD__(dvd_id				,obj_id					,v ,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pub_id				,obj_id					,v ,default				,Publisher id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pub_seq				,seq_num				,v ,default				,Publisher seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,v ,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,v ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_id				,obj_id					,zv,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pub_id				,obj_id					,zv,default				,Publisher id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pub_seq				,seq_num				,zv,default				,Publisher seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,zv,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zv,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// eddir
	// ------------------------------
FIELD__(dvd_id				,obj_id					,d ,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(person_id			,obj_id					,d ,default				,Director id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(dir_seq				,seq_num				,d ,default				,Director seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,d ,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,d ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_id				,obj_id					,zd,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(person_id			,obj_id					,zd,default				,Director id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(dir_seq				,seq_num				,zd,default				,Director seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,zd,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zd,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// person
	// ------------------------------
FIELD__(person_id			,obj_id					,c ,default				,Person id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(version_id			,version_id				,c ,default				,Current version,0,"",0,0),
FIELD__(alias_of			,obj_id					,c ,default				,Alias of id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(alias_of_name		,name_long				,c ,default				,Alias of,CField::eDbDashOnEmpty,"",0,0),
FIELD__(surname				,name					,c ,default				,Surname,CField::eDbDashOnEmpty,"",0,0),
FIELD__(given_name			,name					,c ,default				,Given name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(surname_first_ind	,bool_check				,c ,default				,Surname comes first,0,"",0,0),
FIELD__(display_name		,name					,c ,default				,Display name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(name_nocase			,name_long				,c ,default				,Name search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(url					,url					,c ,default				,DVDAF URL,CField::eDbDashOnEmpty,"",0,0),
FIELD__(father_id			,obj_id					,c ,default				,Father id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(father_name			,name_long				,c ,default				,Father,CField::eDbDashOnEmpty,"",0,0),
FIELD__(mother_id			,obj_id					,c ,default				,Mother id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(mother_name			,name_long				,c ,default				,Mother,CField::eDbDashOnEmpty,"",0,0),
FIELD__(country_birth		,country_birth			,c ,default				,Country of birth,0,"",0,0),
FIELD__(state_birth			,state					,c ,default				,State or province,CField::eDbDashOnEmpty,"",0,0),
FIELD__(city_birth			,city					,c ,default				,City of birth,CField::eDbDashOnEmpty,"",0,0),
FIELD__(date_of_birth		,text_dd				,c ,default				,Date of birth,CField::eDbDashOnEmpty,"",0,0),
FIELD__(date_of_death		,text_dd				,c ,default				,Date of death,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,c ,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,c ,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id				,c ,default				,Imdb link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,c ,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_status			,pic_type				,c ,default				,Picture status,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,c ,default				,Picture filename,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_count			,num_pics				,c ,default				,Number of pictures,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(mod_flags			,mod_flags				,c ,default				,Mod flags,CField::eDbDashOnEmpty,"",0,0),
FIELD__(person_created_tm	,datetime				,c ,default				,Created on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(person_updated_tm	,datetime				,c ,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(person_updated_by	,user_id				,c ,default				,Last updated by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(last_justify		,justify_narrow			,c ,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(person_verified_tm	,datetime				,c ,default				,Verified on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(person_verified_by	,user_id				,c ,default				,Verified by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(verified_version	,version_id				,c ,default				,Last verified version,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(person_edit_id		,edit_id				,c ,default				,Person audit id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,c ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(person_edit_id		,edit_id				,zc,default				,Person audit id,0,"",0,0),
FIELD__(person_id			,obj_id					,zc,default				,Person id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(request_cd			,request_cd_person		,zc,default				,Request type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(disposition_cd		,disposition_cd			,zc,default				,Disposition,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_id			,user_id				,zc,default				,Proposer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_notes		,proposer_notes			,zc,default				,Proposer notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposed_tm			,datetime				,zc,default				,Proposed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(updated_tm			,datetime				,zc,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(reviewer_id			,user_id				,zc,default				,Reviewer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewer_notes		,reviewer_notes			,zc,default				,Moderator notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewed_tm			,datetime				,zc,default				,Reviewed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,zc,default				,Version,0,"",0,0),
FIELD__(alias_of			,obj_id					,zc,default				,Alias of,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(surname				,name					,zc,default				,Surname,CField::eDbDashOnEmpty,"",0,0),
FIELD__(given_name			,name					,zc,default				,Given name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(surname_first_ind	,bool_check				,zc,default				,Surname comes first,0,"",0,0),
FIELD__(father_id			,obj_id					,zc,default				,Father,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(mother_id			,obj_id					,zc,default				,Mother,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(country_birth		,country_birth			,zc,default				,Country of birth,0,"",0,0),
FIELD__(state_birth			,state					,zc,default				,State or province,CField::eDbDashOnEmpty,"",0,0),
FIELD__(city_birth			,city					,zc,default				,City of birth,CField::eDbDashOnEmpty,"",0,0),
FIELD__(date_of_birth		,text_dd				,zc,default				,Date of death,CField::eDbDashOnEmpty,"",0,0),
FIELD__(date_of_death		,text_dd				,zc,default				,Date of birth,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,zc,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,zc,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(imdb_id				,imdb_id				,zc,default				,Imdb link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(youtube_id			,youtube_id				,zc,default				,YouTube link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(update_justify		,justify_wide			,zc,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zc,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// role
	// ------------------------------
FIELD__(film_id				,obj_id					,r ,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(person_id			,obj_id					,r ,default				,Person id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(person_role			,person_role			,r ,default				,Role type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(seq_num				,seq_num				,r ,default				,Role seq,0,"",0,0),
FIELD__(character_name		,name_long				,r ,default				,Character name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(role_type			,role_type				,r ,default				,Role scope,CField::eDbDashOnEmpty,"",0,0),
FIELD__(credited_ind		,bool_check				,r ,default				,Credited,0,"",0,0),
FIELD__(role_cmts			,role_cmts				,r ,default				,Comments,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,r ,default				,Picture filename,CField::eDbDashOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,r ,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,r ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_edit_id		,edit_id				,zr,default				,Film audit id,0,"",0,0),
FIELD__(person_id			,obj_id					,zr,default				,Person id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(person_role			,person_role			,zr,default				,Role type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(seq_num				,seq_num				,zr,default				,Role seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(film_id				,obj_id					,zr,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(character_name		,name_long				,zr,default				,Character name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(role_type			,role_type				,zr,default				,Role scope,CField::eDbDashOnEmpty,"",0,0),
FIELD__(credited_ind		,bool_check				,zr,default				,Credited,0,"",0,0),
FIELD__(role_cmts			,role_cmts				,zr,default				,Comments,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,zr,default				,Picture filename,CField::eDbDashOnEmpty,"",0,0),
FIELD__(sort_order			,sort_order				,zr,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zr,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// title
	// ------------------------------
FIELD__(film_id				,obj_id					,t ,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(title_seq			,seq_num_small			,t ,default				,Alternate seq,0,"",0,0),
FIELD__(title				,film_title_alternate	,t ,default				,Alternate title,CField::eDbDashOnEmpty,"",0,0),
FIELD__(title_sort			,film_title_single		,t ,default				,Alternate order,CField::eDbDashOnEmpty,"",0,0),
FIELD__(title_search		,film_title_single		,t ,default				,Title search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(search_article_ind	,bool_check				,t ,default				,Add article to search,0,"",0,0),
FIELD__(sort_order			,sort_order				,t ,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(used_in_edition_ind	,bool_check				,t ,default				,Title in use,0,"",0,0),
FIELD__(creation_seed		,seed					,t ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(film_edit_id		,edit_id				,zt,default				,Film audit id,0,"",0,0),
FIELD__(title_seq			,seq_num_small			,zt,default				,Alternate seq,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(film_id				,obj_id					,zt,default				,Film id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(title				,film_title_alternate	,zt,default				,Alternate title,CField::eDbDashOnEmpty,"",0,0),
FIELD__(title_sort			,film_title_single		,zt,default				,Alternate order,CField::eDbDashOnEmpty,"",0,0),
FIELD__(title_search		,film_title_single		,zt,default				,Title search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(search_article_ind	,bool_check				,zt,default				,Add article to search,0,"",0,0),
FIELD__(sort_order			,sort_order				,zt,default				,Sort,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zt,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// pub
	// ------------------------------
FIELD__(pub_id				,obj_id					,u ,default				,Publisher id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(version_id			,version_id				,u ,default				,Current version,0,"",0,0),
FIELD__(pub_name			,name					,u ,default				,Publisher name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pub_name_nocase		,pub_name_nocase		,u ,default				,Search string,CField::eDbDashOnEmpty,"",0,0),
FIELD__(url					,url					,u ,default				,DVDAF URL,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,u ,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,u ,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(mod_flags			,mod_flags				,u ,default				,Mod flags,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pub_created_tm		,datetime				,u ,default				,Created on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pub_updated_tm		,datetime				,u ,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pub_updated_by		,user_id				,u ,default				,Last updated by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(last_justify		,justify_narrow			,u ,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pub_verified_tm		,datetime				,u ,default				,Verified on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pub_verified_by		,user_id				,u ,default				,Verified by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(verified_version	,version_id				,u ,default				,Last verified version,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(pub_edit_id			,edit_id				,u ,default				,Publisher audit id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,u ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pub_edit_id			,edit_id				,zu,default				,Publisher audit id,0,"",0,0),
FIELD__(pub_id				,obj_id					,zu,default				,Publisher id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(request_cd			,request_cd_pub			,zu,default				,Request type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(disposition_cd		,disposition_cd			,zu,default				,Disposition,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_id			,user_id				,zu,default				,Proposer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_notes		,proposer_notes			,zu,default				,Proposer notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposed_tm			,datetime				,zu,default				,Proposed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(updated_tm			,datetime				,zu,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(reviewer_id			,user_id				,zu,default				,Reviewer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewer_notes		,reviewer_notes			,zu,default				,Moderator notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewed_tm			,datetime				,zu,default				,Reviewed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,zu,default				,Version,0,"",0,0),
FIELD__(pub_name			,name					,zu,default				,Publisher name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(official_site		,url					,zu,default				,Official Site,CField::eDbDashOnEmpty,"",0,0),
FIELD__(wikipedia			,url					,zu,default				,Wikipedia link,CField::eDbDashOnEmpty,"",0,0),
FIELD__(update_justify		,justify_wide			,zu,default				,Update justification for last version,CField::eDbDashOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zu,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
	// ------------------------------
	// pic
	// ------------------------------
FIELD__(pic_id				,pic_id					,p ,default				,Picture id,0,"",0,0),
FIELD__(version_id			,version_id				,p ,default				,Current version,0,"",0,0),
FIELD__(sub_version_id		,version_id				,p ,default				,Current subversion,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name				,p ,default				,Picture name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_type			,pic_type_2				,p ,default				,Picture type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(transforms			,transforms				,p ,default				,Transforms,CField::eDbDashOnEmpty,"",0,0),
FIELD__(caption				,caption				,p ,default				,Picture caption text,CField::eDbDashOnEmpty,"",0,0),
FIELD__(copy_holder			,copyright				,p ,default				,Copyright holder,CField::eDbDashOnEmpty,"",0,0),
FIELD__(copy_year			,year					,p ,default				,Copyright year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(suitability_cd		,suitability_cd			,p ,default				,Image suitability,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_dx				,num_pixels				,p ,default				,Uploaded picture width,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_dy				,num_pixels				,p ,default				,Uploaded picture height,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_uploaded_tm		,datetime				,p ,default				,Uploaded on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pic_uploaded_by		,user_id				,p ,default				,Uploaded by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_edited_tm		,datetime				,p ,default				,Last edited on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pic_edited_by		,user_id				,p ,default				,Last edited by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_verified_tm		,datetime				,p ,default				,Verified on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(pic_verified_by		,user_id				,p ,default				,Verified by,CField::eDbDashOnEmpty,"",0,0),
FIELD__(verified_version	,version_id				,p ,default				,Last verified version,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(pic_edit_id			,edit_id				,p ,default				,Picture audit id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,p ,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(img_treatment		,img_treatment			,p ,default				,Treatment,CField::eDbDashOnEmpty,"",0,0),
FIELD__(rot_degrees			,rot_degree				,p ,default				,Rotation in degrees,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(rot_degrees_x		,rot_pixel				,p ,default				,Rotation in x pixels,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_x1				,crop_pixel				,p ,default				,Left margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_x2				,crop_pixel				,p ,default				,Right margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_y1				,crop_pixel				,p ,default				,Upper margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_y2				,crop_pixel				,p ,default				,Lower margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_fuzz			,crop_fuzz				,p ,default				,Autocrop fuzz,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(black_pt			,black_pt				,p ,default				,Levels black point,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(white_pt			,white_pt				,p ,default				,Levels white point,0,"",0,0),
FIELD__(gamma				,gamma					,p ,default				,Gamma adustment,0,"",0,0),
FIELD__(obj_edit_id			,edit_id				,zp,default				,Audit id,0,"",0,0),
FIELD__(obj_id				,obj_id					,zp,default				,Obj id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(obj_type			,obj_type				,zp,default				,Type of object,0,"",0,0),
FIELD__(pic_id				,pic_id					,zp,default				,Picture id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_edit_id			,edit_id				,zp,default				,Picture audit id,0,"",0,0),
FIELD__(request_cd			,request_cd_pic			,zp,default				,Request type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(disposition_cd		,disposition_cd			,zp,default				,Disposition,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_id			,user_id				,zp,default				,Proposer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposer_notes		,proposer_notes			,zp,default				,Proposer notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(proposed_tm			,datetime				,zp,default				,Proposed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(updated_tm			,datetime				,zp,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(reviewer_id			,user_id				,zp,default				,Reviewer id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewer_notes		,reviewer_notes			,zp,default				,Moderator notes,CField::eDbDashOnEmpty,"",0,0),
FIELD__(reviewed_tm			,datetime				,zp,default				,Reviewed on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(uploaded_pic		,filename				,zp,default				,Uploaded file,CField::eDbDashOnEmpty,"",0,0),
FIELD__(hist_version_id		,version_id				,zp,default				,Version,0,"",0,0),
FIELD__(hist_sub_version_id	,version_id				,zp,default				,Subversion,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_name			,pic_name_long			,zp,default				,Picture name,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_type			,pic_type_2				,zp,default				,Picture type,CField::eDbDashOnEmpty,"",0,0),
FIELD__(transforms			,transforms				,zp,default				,Transforms,CField::eDbDashOnEmpty,"",0,0),
FIELD__(caption				,caption				,zp,default				,Picture caption text,CField::eDbDashOnEmpty,"",0,0),
FIELD__(copy_holder			,copyright				,zp,default				,Copyright holder,CField::eDbDashOnEmpty,"",0,0),
FIELD__(copy_year			,year					,zp,default				,Copyright year,CField::eDbZeroOnEmpty,"(new Date()).getFullYear()",0,0),
FIELD__(suitability_cd		,suitability_cd			,zp,default				,Image suitability,CField::eDbDashOnEmpty,"",0,0),
FIELD__(pic_dx				,num_pixels				,zp,default				,Uploaded picture width,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(pic_dy				,num_pixels				,zp,default				,Uploaded picture height,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(creation_seed		,seed					,zp,default				,Creation seed,CField::eDbDashOnEmpty,"",0,0),
FIELD__(img_treatment		,img_treatment			,zp,default				,Treatment,CField::eDbDashOnEmpty,"",0,0),
FIELD__(rot_degrees			,rot_degree				,zp,default				,Rotation in degrees,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(rot_degrees_x		,rot_pixel				,zp,default				,Rotation in x pixels,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_x1				,crop_pixel				,zp,default				,Left margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_x2				,crop_pixel				,zp,default				,Right margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_y1				,crop_pixel				,zp,default				,Upper margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_y2				,crop_pixel				,zp,default				,Lower margin crop,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(crop_fuzz			,crop_fuzz				,zp,default				,Autocrop fuzz,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(black_pt			,black_pt				,zp,default				,Levels black point,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(white_pt			,white_pt				,zp,default				,Levels white point,0,"",0,0),
FIELD__(gamma				,gamma					,zp,default				,Gamma adustment,0,"",0,0),
	// ------------------------------
	// price
	// ------------------------------
FIELD__(upc					,upc					,pr,default				,UPC,CField::eDbDashOnEmpty,"",0,0),
FIELD__(price_00			,money_null				,pr,default				,Vendor 0 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_01			,money_null				,pr,default				,Vendor 1 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_02			,money_null				,pr,default				,Vendor 2 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_03			,money_null				,pr,default				,Vendor 3 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_04			,money_null				,pr,default				,Vendor 4 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_05			,money_null				,pr,default				,Vendor 5 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_06			,money_null				,pr,default				,Vendor 6 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_07			,money_null				,pr,default				,Vendor 7 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_08			,money_null				,pr,default				,Vendor 8 price,CField::eDbNullOnEmpty,"",0,0),
FIELD__(price_09			,money_null				,pr,default				,Vendor 9 price,CField::eDbNullOnEmpty,"",0,0),
	// ------------------------------
	// my_dvd
	// ------------------------------
FIELD__(user_id				,user_id				,b ,default				,User id,CField::eDbDashOnEmpty,"",0,0),
FIELD__(dvd_id				,obj_id					,b ,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD__(folder				,folder					,b ,default				,Folder,CField::eDbDashOnEmpty,"",0,0),
FIELD__(sort_text			,sort_text				,b ,default				,Sort text,CField::eDbDashOnEmpty,"",0,0),
FIELD__(public_ind			,bool_pub_ind			,b ,default				,Public indicator,0,"",0,0),
FIELD__(genre_overwrite		,genre_cd_2				,b ,my_dvd_genre		,Genre override,0,"",0,0),
FIELD__(pic_overwrite		,pic_name				,b ,default				,Picture override,CField::eDbDashOnEmpty/*|FIELD_NEED_VIEW_USER*/,"",0,0),
FIELD__(user_film_rating	,star_rating			,b ,default				,Film rating,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(user_dvd_rating		,star_rating			,b ,default				,DVD rating,CField::eDbMinus1OnEmpty,"",0,0),
FIELD__(comments			,comments				,b ,default				,Comments,CField::eDbNullOnEmpty/*|FIELD_NEED_VIEW_USER*/,"",0,0),
FIELD__(owned_dd			,user_date				,b ,default				,Date of purchase,CField::eDbDashOnEmpty,"",0,0),
FIELD__(my_dvd_created_tm	,datetime				,b ,default				,Created on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(my_dvd_updated_tm	,datetime				,b ,default				,Last updated on,CField::eDbNullOnEmpty,"",0,0),
FIELD__(my_dvd_expire_tm	,datetime				,b ,default				,Expired time,CField::eDbNullOnEmpty,"",0,0),
FIELD_2(user_id				,user_id				,b2,default				,User id,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(dvd_id				,obj_id					,b2,default				,DVD id,CField::eDbZeroOnEmpty,"",0,0),
FIELD_2(last_watched_dd		,user_date				,b2,default				,Date last watched,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(retailer			,retailer				,b2,default				,Retailer,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(price_paid			,money					,b2,default				,Price paid,CField::eDbMinus1OnEmpty,"",0,0),
FIELD_2(order_dd			,user_date				,b2,default				,Order date,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(order_number		,order_number			,b2,default				,Order number,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(trade_loan			,trade_loan_cd			,b2,default				,Trade or loan,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(loaned_to			,loaned_to				,b2,default				,Loaned to,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(loan_dd				,user_date				,b2,default				,Loan date,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(return_dd			,user_date				,b2,default				,Return date,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(asking_price		,money					,b2,default				,Asking price,CField::eDbMinus1OnEmpty,"",0,0),
FIELD_2(custom_1			,custom_text			,b2,default				,Custom 1,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(custom_2			,custom_text			,b2,default				,Custom 2,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(custom_3			,custom_text			,b2,default				,Custom 3,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(custom_4			,custom_text			,b2,default				,Custom 4,CField::eDbDashOnEmpty,"",0,0),
FIELD_2(custom_5			,custom_text			,b2,default				,Custom 5,CField::eDbDashOnEmpty,"",0,0),

FIELDzz(a_director			,director				,a ,dvd_director		,Director			),
FIELDzz(a_publisher			,publisher				,a ,dvd_publisher		,DVD publisher		),
FIELDzz(a_genre				,genre					,a ,dvd_effective_genre	,Primary genre		)};

// ------------------------------
// special formatting
// ------------------------------
//FIELD_Z(z,z,check				,Select				,NULL				,FIELD_NEED_OBJ_ID		),
//FIELD_Z(z,z,row_sort_del		,Sort / Del			,NULL				,FIELD_NEED_ROW_NO		),
//FIELD_Z(x,a,pic					,Picture			,_gp_pic_dvd		,0						),
//FIELD_Z(x,f,pic					,Picture			,_gp_pic_film		,0						),
//FIELD_Z(x,c,pic					,Picture			,_gp_pic_person		,0						),
//FIELD_Z(x,a,vid					,Video				,_gp_vid_dvd		,0						),
//FIELD_Z(x,f,vid					,Video				,_gp_vid_film		,0						),
//FIELD_Z(x,c,vid					,Video				,_gp_vid_person		,0						),
//FIELD_Z(x,f,title_matrix		,Title				,NULL				,0						),
//FIELD_Z(x,f,director_matrix		,Directors			,NULL				,0						),
//FIELD_Z(x,f,cast_matrix			,Cast				,NULL				,0						),
//FIELD_Z(x,f,crew_matrix			,Crew				,NULL				,0						),
//FIELD_Z(x,f,dvd_pub_matrix		,Publisher			,NULL				,0						),
//FIELD_Z(x,f,dvd_dir_matrix		,Director			,NULL				,0						),
//FIELD_Z(x,c,display_name		,Name				,_gp_person_name	,0						),
//FIELD_Z(x,r,role_dir			,Director			,_gp_role			,0						),
//FIELD_Z(x,r,role_cast			,Cast				,_gp_role			,0						),
//FIELD_Z(x,r,role_crew			,Crew				,_gp_role			,0						),
//FIELD_Z(z,z,dvd_publisher		,DVD publisher		,_gp_dvd_publisher	,0						),
//FIELD_Z(z,z,links				,Links				,_gp_links			,FIELD_NEED_OBJ_ID		),
//FIELD_Z(z,z,row_number			,Row Number			,NULL				,FIELD_NEED_ROW_NO		),
//FIELD_Z(z,z,screening			,Film release date	,_gp_film_rel_dd	,0						),
//FIELD_Z(z,z,text				,Text				,NULL				,0						),
//FIELD_Z(z,z,title				,Title				,_gp_title			,0						),
//FIELD_Z(z,z,title_2				,Title				,_gp_title_2		,0						),
//FIELD_Z(z,z,cart				,Cart				,NULL				,FIELD_NEED_OBJ_ID		),
//FIELD_Z(z,z,price_comparison	,Price Comparison	,NULL				,0						),
//FIELD_Z(z,z,best_price			,Best				,NULL				,CField::eDbZeroOnEmpty	)};
